require("lazy").setup({
	spec = {
		require("core.mason"),
		require("core.autopairs"),
		require("core.fidget"),
		require("core.completion"),
		require("core.luasnip"),
		require("core.friendly-snippets"),
		require("core.treesitter"),
		require("core.lazydev"),
		require("core.neoconf"),
		require("core.undotree"),
		require("core.telescope"),
		require("core.which-key"),
		require("appearance"),
		require("navigation"),
		require("tools"),
		require("debugging"),
	},
	change_detection = { notify = false },
})
